### ISSUE TITLE
Userの role をどう管理、設定するか

### ISSUE THREAD

**Issue by yusuke-eto** [nr27bypphy/Glenfiddich#29]
### 概要
ユーザーにはロールが存在するが、それをどうやって設定、管理するか？
ユーザーの追加方法としては、サインアップとユーザー招待(ダッシュボード画面で追加できる予定。現在未実装)があるが、ユーザー招待で設定できるようにすべき？
また、サインアップで入るのは、基本的にオーナーっていう感じになるのか？

そのあたりの動線や、設定方法がちゃんと把握できてないので
把握して、実装する必要がある。

### 前提
Userには role が存在する
-> オーナー、管理者、通常、ゲスト

### ロールの目的
ロールによって、可能なアクションを制御する

**Comment by ktashiro0429** [comment]
1.
> ユーザーにはロールが存在するが、それをどうやって設定、管理するか？

最初にアカウント発行をした人（Slackでいうワークスペース開設[登録]をした人）がオーナーに設定されていて、User管理ページでそれぞれのロールを変更できる想定。アカウント発行は大きく分けて 1 .自分のプロフィール設定 + 2. チームの名前設定 かな


2. 
> ユーザーの追加方法としては、サインアップとユーザー招待(ダッシュボード画面で追加できる予定。現在未実装)があるが、ユーザー招待で設定できるようにすべき？

MVPではユーザー招待のみで追加されるようにしようか。


3. 
> また、サインアップで入るのは、基本的にオーナーっていう感じになるのか？

上述してしまったんだけど、そのイメージ！

**Comment by yusuke-eto** [comment]
### サインアップ
- 自分のプロフィール設定
- チームの名前設定

### ユーザーが使用開始するためには
- オーナーがユーザー管理画面で招待

**ダッシュボード= ユーザー管理画面**
オーナー -> ユーザー削除出来る
管理者 -> ユーザー削除出来ない
