### ISSUE TITLE
メンバーの追加を出来るようにする

### ISSUE THREAD

**Issue by yusuke-eto** [nr27bypphy/Glenfiddich#32]
### 概要
ダッシュボードでメンバーの追加ボタンがあるので、
メンバーの追加が出来るはずだが、現在はまだ未実装
なので、ダッシュボードからメンバーの追加を可能にする

### 考慮点
- 追加のモーダルでは何を入力できるようにするか？
- 追加した時は仮パスワードを発行し、メールに送信するなどのプロセスにするか？
↑ 可能だが、ちょっと実装したことないので、時間がかかりそう(普通に仕事して2~3人/日ぐらい)

- 一旦追加の段階でpasswordも入力できるようにして、あとでpassword変更画面で変更してもらう
↑これだとコストは低め。すぐにできそうだが、パスワード変更画面を別途作る必要がある
けど、パスワード変更画面はどのみち作らないといけないので、今やるか後でやるかの問題な気もしている

### いつまで
12/11には遅くても出来そう

**Comment by yusuke-eto** [comment]
一旦コスト的に低いし、手戻りも少ないので、passwordを入力する方針で進めておきます🙇‍♂️
API側の実装も

**Comment by ktashiro0429** [comment]
passwordに関しては違和感なし

> 追加のモーダルでは何を入力できるようにするか？
これに関しては、一旦メールアドレスのみでいい認識かな
ゆくゆくはプロジェクトへのアサインとかもしちゃうようなイメージは持っているがまだ具体化できていない

**Comment by yusuke-eto** [comment]
こちらに関しては、ゆくゆくはメール招待でハイパーリンク踏んでもらうみたいな感じにしたいが、優先度自体は高じゃないので、
後回しでも良い
